### ISSUE TITLE
[Bug] Elseif in IfStatement Not working

### ISSUE THREAD

**Issue by ghost** [bastinald/malzahar#3]
In the `Home` component I created a property for `$color` and then a constructor to set it

```
public string $color;

public function __construct()
{
    $this->color = 'blue';
}
```

Then using your example if statement from the README in my template function I placed this:

```
Statement::if($this->color == 'red',
    Html::h1(__('The color is red!'))
        ->class('text-red-600'),
)->elseif($this->color == 'blue',
    Html::h2(__('The color is blue!'))
        ->class('text-blue-600'),
)->else(
    Html::h3(__('The color is something else!')),
)
```

When rendering the page I get

```
The color is something else!
```

Perhaps this isn't a bug and just needs to return earlier?

**Comment by ghost** [comment]
Logically it seems that setting the condition in the else method to true by default will override the condition in the elseif method.

If I dump `$this->conditions` in the elseif method it shows it correctly set as true for the blue color, but it fails to return it properly.

```
array:2 [▼
  0 => "<h1 class="text-red-600">The color is red!</h1>"
  1 => "<h2 class="text-blue-600">The color is blue!</h2>"
]
```
But the execution continues to the else method even though the the condition in elseif it true.

**Comment by ghost** [comment]
I added a new method to search for true values in the existing array and it's called prior to setting the each condition

```
/**
 * Determine if the else condition should be set to true or false.
 *
 * @return boolean
 */
public function findOrFail(): bool
{
    foreach ($this->conditions as $key => $condition) {
        if ($key) {
            return false;
        }
    }

    return true;
}
```

Now else looks like so:

```
/**
 * Else conditions handler.
 *
 * @param  \Bastinald\Malzahar\Contracts\ComponentInterface ...$slot
 * @return \Bastinald\Malzahar\Statements\IfStatement
 */
public function else(ComponentInterface ...$slot): IfStatement
{
    $condition = $this->findOrFail();
    
    $this->conditions[$condition] = implode($slot);

    return $this;
}
```

Now when I render I get `blue` for blue and `other color` for anything other than blue or red.

Will submit

**Comment by bastinald** [comment]
It needs to be changed to use a closure instead of `...$slot` for all the methods.

I ran into this bug, it has to use a closure, because your statements may contain code that shouldn't run if a condition isn't met. Right now, it tries to compile all code inside of the closures and only shows what condition is met.

**Comment by bastinald** [comment]
It needs to be changed to something like this:

    <?php

    namespace Bastinald\Malzahar\Statements;

    use Bastinald\Malzahar\Contracts\ComponentInterface;

    class IfStatement
    {
        /**
        * Local conditions array.
        *
        * @var array
        */
        public array $conditions = [];

        /**
        * Create a new instance of the class.
        *
        * @param bool|null $condition
        * @param closure $callback
        */
        public function __construct(?bool $condition, closure $callback)
        {
            $this->conditions[$condition] = $callback;
        }

        /**
        * Else if condition handler.
        *
        * @param  bool|null $condition
        * @param closure $callback
        * @return \Bastinald\Malzahar\Statements\IfStatement
        */
        public function elseif(?bool $condition, closure $callback): IfStatement
        {
            $this->conditions[$condition] = $callback;
            
            return $this;
        }

        /**
        * Else conditions handler.
        *
        * @param closure $callback
        * @return \Bastinald\Malzahar\Statements\IfStatement
        */
        public function else(closure $callback): IfStatement
        {
            $condition = $this->findOrFail();
            
            $this->conditions[$condition] = $callback;

            return $this;
        }

        /**
        * Return callback as a string.
        *
        * @return string
        */
        public function __toString(): string
        {
            foreach ($this->conditions as $condition => $callback) {
                if ($condition) {
                    return $callback();
                }
            }

            return '';
        }
    }

And to use it in a template:

    Statement::if($this->label,
        fn() => Html::label($this->label),
    ),

Notice how I'm now using a `fn()` as the parameter if the condition passes.

We need it this way because its compiling everything in the statement, it needs to only compile if the condition is met.

If you submit a PR for the class and the readme I will pull. Just review it cause I just threw that together quickly and it probably has bugs.

**Comment by ghost** [comment]
Cool I'll write and test it and see where we stand.

This will remove the type hint for the interface, but I'll leave it on the components for now.

Looking back now at the each statement I raised before ... I think the proper way to handle this will be to make a change in `Statement` itself and see if we already have a Collection passed in, then if we don't we can wrap it there and pass it to EachStatement.

You'll see it in the PR.

**Comment by ghost** [comment]
Maybe Im misunderstanding ... I assumed this was to remove the need for the `findOrFail` checking that I added.

But even passing the callback still required it to be checked, so basically it was working fine with the slot after the PR was merged, and now it works fine with the callback, but still requires us to check else and set the condition dynamically.

**Comment by bastinald** [comment]
We still need to add the callback

**Comment by bastinald** [comment]
You shouldn't need `findOrFail` anymore to be honest.

**Comment by ghost** [comment]
Well it doesn't work without it.

If I have red or blue as the color I still get `other color` unless we check whether to set the else condition to true or false.

**Comment by bastinald** [comment]
Else should be this:

```php
    public function else(closure $callback): IfStatement
    {
        $this->conditions[true] = $callback;

        return $this;
    }
```

Else should always have a condition of `true`.

**Comment by bastinald** [comment]
I think I see the problem actually, multiple array keys being `true` would cause problems.

So the entire class should be changed to something like this:

```php
<?php

namespace Bastinald\Malzahar\Statements;

use Closure;

class IfStatement
{
    /**
     * Local conditions array.
     *
     * @var array
     */
    public array $conditions = [];

    /**
     * Create a new instance of the class.
     *
     * @param bool|null $condition
     * @param \Closure $callback
     */
    public function __construct(?bool $condition, Closure $callback)
    {
        $this->conditions[] = [$condition, $callback];
    }

    /**
     * Else if condition handler.
     *
     * @param  bool|null $condition
     * @param  \Closure $callback
     * @return \Bastinald\Malzahar\Statements\IfStatement
     */
    public function elseif(?bool $condition, Closure $callback): IfStatement
    {
        $this->conditions[] = [$condition, $callback];

        return $this;
    }

    /**
     * Else conditions handler.
     *
     * @param  \Closure $callback
     * @return \Bastinald\Malzahar\Statements\IfStatement
     */
    public function else(Closure $callback): IfStatement
    {
        $this->conditions[] = [true, $callback];

        return $this;
    }

    /**
     * Loop conditions and execute the callback.
     *
     * @return string
     */
    public function __toString(): string
    {
        foreach ($this->conditions as $condition) {
            if ($condition[0]) {
                $callback = $condition[1];
                
                return $callback();
            }
        }

        return '';
    }
}
```

This should work much better. Let me know your thoughts.

**Comment by ghost** [comment]
Yep ... that did the trick.

Sorry I didn't see it more clearly the first time.

PR coming.
