### ISSUE TITLE
[Conversation]Jetstream Support

### ISSUE THREAD

**Issue by ghost** [bastinald/malzahar#9]
Opening this as a conversion to discuss steps needed to support Jetstream.

> This is support I've added in a personal project, not my fork of Malzahar.

I've installed and customized all the default models (via publishing stubs) to support Jetstream:

* User (Laravel)
* Team (Jetstream)
* Membership (Jetstream)
* TeamInvitation (Jetstream)
* PersonalAccessToken (Sanctum)

Added support to UserSeeder to create teams for each user that's seeded:

```
/**
 * Run the database seeds.
 *
 * @return void
 */
public function run()
{
    User::factory()->withPersonalTeam()->create([
        'email' => 'user@example.com',
    ]);
    
    User::factory(29)->withPersonalTeam()->create();
}
```

The problem I'm seeing is that there are major conflicts with the native Jetstream system since we've changed configuration values for the default Livewire that's installed.

Because all the components and controllers for Jetstream come directly from the package itself and aren't publishable, and Jetstream exports it's own routes, everything from Malzahar is overwritten and not accessed.

Getting a lot of this error:

> Livewire\Exceptions\CorruptComponentPayloadException
Livewire encountered corrupt data when trying to hydrate the [laravel.jetstream.http.livewire.update-profile-information-form] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
http://jetmalz.test/user/profile

 
I think we'll need to create a separate package that includes local components to replace all the Jetstream default components and controllers.

Let me know your thoughts.

**Comment by ghost** [comment]
It seems like these errors are only being produced on `update` and `delete` posts. Accessing get routes and and post `store` routes seems to be working.

**Comment by bastinald** [comment]
I'll accept PR's but I'm currently working on some Bootsrap-based stuff.

I'm finding Tailwind to be tedious for my larger scale apps. :/

**Comment by ghost** [comment]
It's never tedious to have pixel level control over any element on a page. 

I usually tend to create some reusable selectors with @apply for things like inputs, buttons, cards etc. 

Then I'm free to add on to those items in utility mode. 

Don't abandon it, make it work for your workflow.

**Comment by bastinald** [comment]
For jetstream to work, we need to remove the Config::set stuff from the provider, and just have the package create a livewire config file with the values we want. That's the only way around it.

**Comment by ghost** [comment]
So you're thinking just to use all the default Jetstream controllers and classes? 

I'll try removing the config entries and see if that resolves the posting issues.

**Comment by bastinald** [comment]
to be honest im not familiar with jetstream. im working on another package right now that has auth and crud built in, but its using views and a bootstrap component package i just released.

**Comment by ghost** [comment]
I see.

The jetstream controllers and livewire components all live in the vendor package itself as well as the service provider exporting routes to said controllers.

So Malzahar itself won't be compatible without a good deal of work.

Seems like you're off in a different direction now.

**Comment by bastinald** [comment]
yeah this package was more of a concept but im getting frustrated with tailwind and using some legacy stuff is really tricky to do. 

its just frustrating in general because i believe this package shows what the future of backend could be. 

but theres a lot of hoops to jump through and work to be done to get this to the level i want it to be.

**Comment by ghost** [comment]
I guess I don't understand ... Tailwind is a joy to use, what seems to be the issue?

**Comment by ghost** [comment]
Out of curiosity ... would there be much difference in pulling in a Vue component vs a Livewire component into a layout?

Something like:

```
Vue::make('my-vue-component', $data)
    ->class('flex items-center rounded shadow'),
```

Just an idea.

Mix could compile and code split Vue components then the framework could inject that component with props when called.

Though I suppose someone could just as easily use Inertia.

**Comment by bastinald** [comment]
its a good idea but then you need to use inertia or vue router and it introduces all the awesome complexities that come with SPA

**Comment by ghost** [comment]
No you don't. You're already routing to existing blade templates.

I don't use Inertia or Vue Router in any of my existing Laravel apps and all the Vue components work just fine.
